server:
  port: 8080

spring:
  application:
    name: docgiatruyen-backend-core
  datasource:
    url: jdbc:mysql://localhost:3306/docgiatruyen?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437 # Example 256-bit secret key (Hex)
    expirationMs: 86400000 # 24 hours
